#!/usr/bin/env bash

# EAS Build Post-Install Hook
# Fix Firebase provider conflict in AndroidManifest

set -e

echo "🔧 Fixing Firebase provider conflict..."
echo "📦 New package: site.ezyfix.app"

MANIFEST_PATH="android/app/src/main/AndroidManifest.xml"

if [ -f "$MANIFEST_PATH" ]; then
  echo "📝 Found AndroidManifest.xml"
  
  # Add tools namespace if not exists
  if ! grep -q 'xmlns:tools=' "$MANIFEST_PATH"; then
    echo "➕ Adding tools namespace"
    sed -i 's/<manifest/<manifest xmlns:tools="http:\/\/schemas.android.com\/tools"/' "$MANIFEST_PATH"
  fi
  
  # Add tools:replace to FirebaseInitProvider
  if grep -q 'FirebaseInitProvider' "$MANIFEST_PATH"; then
    echo "🔥 Adding tools:replace to Firebase provider"
    sed -i 's/\(android:name=".*FirebaseInitProvider"\)/\1 tools:replace="android:authorities"/' "$MANIFEST_PATH"
  fi
  
  echo "✅ Firebase conflict fixed!"
else
  echo "⚠️ AndroidManifest.xml not found (will be generated by Expo)"
fi

echo "✅ Post-install hook completed"
